# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /blog/:title/

# Setup
title:               monnoval
tagline:             ''
description:         ''
url:                 http://monnoval.com
baseurl:             /
paginate:            5
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Mon Noval
  url:               https://twitter.com/monnoval
  email:             mon@monnoval.com

# Custom vars
version:             1.0.0
